branches:
  only:
    - master
language: node_js
node_js:
- lts/*
git:
  depth: 3
install:
- yarn --frozen-lockfile
after_success:
  - yarn release
cache: yarn
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
